export const APP_CONFIG = {
  APP_NAME: 'Hybrid Mobile App',
  APP_VERSION: '1.0.0',

  DEFAULT_PAGE_SIZE: 10,
  MAX_PAGE_SIZE: 50,

  TOKEN_STORAGE_KEY: 'auth_token',
  USER_STORAGE_KEY: 'user_data',
  TOKEN_EXPIRY_HOURS: 24,

  API_TIMEOUT: 10000,
  RETRY_ATTEMPTS: 3,
  RETRY_DELAY: 1000,

  STALE_TIME: 5 * 60 * 1000,
  CACHE_TIME: 10 * 60 * 1000,

  SEARCH_DEBOUNCE_DELAY: 300,
  MIN_SEARCH_LENGTH: 2,

  TOAST_DURATION: 4000,
  LOADING_DELAY: 200,

  MOBILE_BREAKPOINT: 768,
  TABLET_BREAKPOINT: 1024,
} as const

export const STORAGE_KEYS = {
  AUTH_TOKEN: APP_CONFIG.TOKEN_STORAGE_KEY,
  USER_DATA: APP_CONFIG.USER_STORAGE_KEY,
  THEME: 'theme_preference',
  LANGUAGE: 'language_preference',
  SEARCH_HISTORY: 'search_history',
} as const
